name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
      # the rest of the steps
      - uses: actions/checkout@v2

      # Caches and restores the bazel build directory.
      # - name: Cache bazel build results
      #   uses: actions/cache@v2.0.0
      #   env:
      #     cache-name: bazel-cache
      #   with:
      #     path: ~/.cache/bazel
      #     key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
      #     restore-keys: |
      #       ${{ runner.os }}-${{ env.cache-name }}-master
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build the code
        run: nix-shell --run "bazel build ..."

      - name: Test the code
        # run: bazel test --test_output=errors --test_tag_filters=-integration-test ...
        run: nix-shell --run "bazel test ..."
